"""add extra_fields to applications

Revision ID: c66b1417e612
Revises: c03cae0cad54
Create Date: 2025-12-30 02:36:27.684566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66b1417e612'
down_revision = 'c03cae0cad54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_fields', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('extra_fields')

    # ### end Alembic commands ###
