"""Add version field to InterviewSlot for optimistic locking

Revision ID: ce7e49246c33
Revises: c66b1417e612
Create Date: 2026-01-31 23:21:46.218139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7e49246c33'
down_revision = 'c66b1417e612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_slots', schema=None) as batch_op:
        # SQLite requires a default value when adding NOT NULL columns to tables with existing data
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_slots', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
